-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 15:13:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- Crear esquema
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- Tabla Hotel
CREATE TABLE IF NOT EXISTS `Hotel` (
  `ID_Hotel` INT NOT NULL AUTO_INCREMENT,
  `Hotel_name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Stars` INT NULL,
  PRIMARY KEY (`ID_Hotel`)
) ENGINE = InnoDB;

-- Tabla Flights
CREATE TABLE IF NOT EXISTS `Flights` (
  `ID_Flight` INT NOT NULL AUTO_INCREMENT,
  `ID_User` INT NULL,
  `Start_date` DATETIME NULL,
  `End_date` DATETIME NULL,
  `Total_cost` DECIMAL(10,2) NULL,
  `Destination` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Flight`)
) ENGINE = InnoDB;

-- Tabla Travel
CREATE TABLE IF NOT EXISTS `Travel` (
  `ID_Travel` INT NOT NULL AUTO_INCREMENT,
  `ID_User` INT NULL,
  `Start_date` DATETIME NULL,
  `End_time` DATETIME NULL,
  `Total_cost` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ID_Travel`)
) ENGINE = InnoDB;

-- Tabla Activity
CREATE TABLE IF NOT EXISTS `Activity` (
  `ID_Activity` INT NOT NULL AUTO_INCREMENT,
  `Activity_Name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Cost` DECIMAL(10,2) NULL,
  `Duration` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Activity`)
) ENGINE = InnoDB;

-- Tabla Payments
CREATE TABLE IF NOT EXISTS `Payments` (
  `ID_Payments` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NULL,
  `Payment_Date` DATETIME NULL,
  `Payment_method` VARCHAR(45) NULL,
  `Transaction_Code` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Payments`)
) ENGINE = InnoDB;

-- Tabla User
CREATE TABLE IF NOT EXISTS `User` (
  `ID_User` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Phone_number` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `MemberShip` TINYINT NULL,
  PRIMARY KEY (`ID_User`)
) ENGINE = InnoDB;

-- Relación Usuario - Pagos (N:M)
CREATE TABLE IF NOT EXISTS `User_has_Payments` (
  `User_ID_User` INT NOT NULL,
  `Payments_ID_Payments` INT NOT NULL,
  PRIMARY KEY (`User_ID_User`, `Payments_ID_Payments`),
  FOREIGN KEY (`User_ID_User`) REFERENCES `User` (`ID_User`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`Payments_ID_Payments`) REFERENCES `Payments` (`ID_Payments`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Relación Travel - Activity (N:M)
CREATE TABLE IF NOT EXISTS `Travel_has_Activity` (
  `Travel_ID_Travel` INT NOT NULL,
  `Activity_ID_Activity` INT NOT NULL,
  PRIMARY KEY (`Travel_ID_Travel`, `Activity_ID_Activity`),
  FOREIGN KEY (`Travel_ID_Travel`) REFERENCES `Travel` (`ID_Travel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`Activity_ID_Activity`) REFERENCES `Activity` (`ID_Activity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;